  version: 1.0
  jobs:
    build:
      docker: 
        - image: circleci/android:api-28-alpha
      steps:
        - checkout # check out the code in the project directory
        - run: echo "hello world" # run the `echo` command
        - run:
          name: Install Dependencies
          command: npm install
        - run:
          name: Install dependencies of the example app
          command: cd example && npm install
